const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();

const MONGODB_URI = process.env.MONGODB_URI || "mongodb+srv://mjachraf:13HeLupR5Cenh3bC@cluster0.kcgsw3w.mongodb.net/game3rb?retryWrites=true&w=majority";

app.use(cors());
app.use(express.json());

let isConnected = false;

async function connectDB() {
    if (isConnected && mongoose.connection.readyState === 1) return;
        try {
                await mongoose.connect(MONGODB_URI, {
                            serverSelectionTimeoutMS: 10000,
                                        socketTimeoutMS: 45000,
                                                    bufferCommands: false,
                                                            });
                                                                    isConnected = true;
                                                                            console.log("Connected to MongoDB!");
                                                                                } catch (err) {
                                                                                        isConnected = false;
                                                                                                console.error("MongoDB connection error:", err);
                                                                                                        throw err;
                                                                                                            }
                                                                                                            }
                                                                                                            
                                                                                                            const gameSchema = new mongoose.Schema({
                                                                                                                id: Number, title: String, platform: String, genre: [String],
                                                                                                                    year: Number, rating: Number, dl: String, img: String,
                                                                                                                        hero: String, hero2: String, hero3: String, link: String,
                                                                                                                            desc: String, hot: Boolean, isNewItem: Boolean, req: Object
                                                                                                                            }, { strict: false });
                                                                                                                            
                                                                                                                            const settingsSchema = new mongoose.Schema({
                                                                                                                                _id: { type: String, default: "global" },
                                                                                                                                    heroLine1: String, heroLine2: String, heroLine3: String,
                                                                                                                                        heroSub: String, aboutText: String
                                                                                                                                        }, { strict: false });
                                                                                                                                        }, { strict: false });
                                                                                                                                        
                                                                                                                                        const adsSchema = new mongoose.Schema({
                                                                                                                                            _id: { type: String, default: "global" },
                                                                                                                                                rightAdEnabled: Boolean, rightAdImage: String, rightAdLink: String
                                                                                                                                                }, { strict: false });
                                                                                                                                                
                                                                                                                                                const Game = mongoose.models.Game || mongoose.model('Game', gameSchema);
                                                                                                                                                const Settings = mongoose.models.Settings || mongoose.model('Settings', settingsSchema);
                                                                                                                                                const Ads = mongoose.models.Ads || mongoose.model('Ads', adsSchema);
                                                                                                                                                
                                                                                                                                                async function seedDatabaseIfNeeded() {
                                                                                                                                                    try {
                                                                                                                                                            const gameCount = await Game.countDocuments();
                                                                                                                                                                    if (gameCount === 0) {
                                                                                                                                                                                const dataPath = path.join(process.cwd(), 'data.json');
                                                                                                                                                                                            if (fs.existsSync(dataPath)) {
                                                                                                                                                                                                            const gamesData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
                                                                                                                                                                                                                            const formattedGames = gamesData.map(g => {
                                                                                                                                                                                                                                                const obj = {...g};
                                                                                                                                                                                                                                                                    if(obj.isNew !== undefined) { obj.isNewItem = obj.isNew; delete obj.isNew; }
                                                                                                                                                                                                                                                                                        return obj;
                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                        await Game.insertMany(formattedGames);
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                } catch (err) { console.error("Seeding error:", err); }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                app.use(async (req, res, next) => {
                                                                                                                                                                                                                                                                                                                                                    try { await connectDB(); next(); }
                                                                                                                                                                                                                                                                                                                                                        catch (err) { res.status(500).json({ error: 'Database connection failed' }); }
                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        app.get('/api/games', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                    let games = await Game.find({}).sort({ id: -1 }).lean();
                                                                                                                                                                                                                                                                                                                                                                            games = games.map(g => { if(g.isNewItem !== undefined) g.isNew = g.isNewItem; return g; });
                                                                                                                                                                                                                                                                                                                                                                                    if (games.length === 0) { await seedDatabaseIfNeeded(); games = await Game.find({}).sort({ id: -1 }).lean(); }
                                                                                                                                                                                                                                                                                                                                                                                            res.json(games);
                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) { res.status(500).json([]); }
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                app.post('/api/games', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                            const newGame = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                    const maxGame = await Game.findOne().sort({ id: -1 });
                                                                                                                                                                                                                                                                                                                                                                                                                            const maxId = maxGame && maxGame.id ? maxGame.id : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                    newGame.id = maxId + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (typeof newGame.genre === 'string') newGame.genre = newGame.genre.split(',').map(g => g.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(newGame.isNew !== undefined) { newGame.isNewItem = newGame.isNew; delete newGame.isNew; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const createdGame = await Game.create(newGame);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true, game: createdGame });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) { res.status(500).json({ success: false, error: err.message }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.put('/api/games/:id', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const id = parseInt(req.params.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const updatedGame = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (typeof updatedGame.genre === 'string') updatedGame.genre = updatedGame.genre.split(',').map(g => g.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(updatedGame.isNew !== undefined) { updatedGame.isNewItem = updatedGame.isNew; delete updatedGame.isNew; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const result = await Game.findOneAndUpdate({ id: id }, updatedGame, { new: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (result) res.json({ success: true, game: result });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else res.status(404).json({ success: false, error: 'Game not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) { res.status(500).json({ success: false, error: err.message }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.delete('/api/games/:id', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const id = parseInt(req.params.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await Game.findOneAndDelete({ id: id });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) { res.status(500).json({ success: false, error: err.message }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.get('/api/settings', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const s = await Settings.findById("global").lean();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(s) return res.json(s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ heroLine1: "Your Ultimate", heroLine2: "Free Gaming", heroLine3: "Destination", heroSub: "Discover free games.", aboutText: "Our mission is to help gamers!" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) { res.status(500).json({}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.post('/api/settings', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await Settings.findOneAndUpdate({ _id: "global" }, req.body, { upsert: true, new: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) { res.status(500).json({ success: false }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.get('/api/ads', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const a = await Ads.findById("global").lean();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(a) return res.json(a);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ rightAdEnabled: false, rightAdImage: "", rightAdLink: "" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) { res.status(500).json({}); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.post('/api/ads', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await Ads.findOneAndUpdate({ _id: "global" }, req.body, { upsert: true, new: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) { res.status(500).json({ success: false }); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = app;
